In [1]:
import numpy as np
import random
import time

In [4]:
a=[]
for _ in range(10**8):
    a.append(random.random())
print('-'*50)
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

--------------------------------------------------
0.2696878910064697 0.055121421813964844


# 4.1 创建一维数组

In [6]:
list1 = [1,2,3,4]
oneArray = np.array(list1) 
print(type(oneArray))  #对象类型
print(list1)
print(oneArray)

# 创建数组的多种形式
# 1. 直接传入列表的方式
t1 = np.array([1,2,3]) 
print(t1) 
print(type(t1))
'''
[1 2 3]
<class 'numpy.ndarray'> '''

# 2. 传入range生成序列
t2 = np.array(range(10)) 
print(t2) 
print(type(t2))
'''
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'> '''

# 3. 使用numpy自带的np.arange()生成数组
t3 = np.arange(0,10,2) 
print(t3) 
print(type(t3))

<class 'numpy.ndarray'>
[1, 2, 3, 4]
[1 2 3 4]
[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 2 4 6 8]
<class 'numpy.ndarray'>


In [7]:
list2 = [[1,2],[3,4],[5,6]]

twoArray = np.array(list2) 
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
# 获取数组的维度( 注意： 与函数的参数很像) 
print(twoArray.ndim)

# 形状（行，列）
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)

2
(3, 2)
6


# 4.4 调整数组形状

In [5]:
four = np.array([[1,2,3],[4,5,6]])

# 修改的是原有的
print(id(four))
four.shape = (3,2) 
print(f'four={four},id(four)={id(four)}')

# 返回一个新的数组
four1 = four.reshape(3,2) 
print(four1)
print(id(four1))

2995710573328
four=[[1 2]
 [3 4]
 [5 6]],id(four)=2995710573328
[[1 2]
 [3 4]
 [5 6]]
2995202587120


In [8]:
five=four.reshape((6,))
five

array([1, 2, 3, 4, 5, 6])

In [9]:
six = four.flatten(order='C')
six

array([1, 2, 3, 4, 5, 6])

In [12]:
# 拓展：数组的形状
t = np.arange(24) 
print(t)
print(t.shape)
# 转换成二维
t1 = t.reshape((2,3,4)) 
print(t1)
print(t1.shape)
t2=t1.reshape((24,))
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# 4.5 数组变列表

In [13]:
# 将数组转成list
a= np.array([9, 12, 88, 14, 25])
list_a = a.tolist() 
list_a

[9, 12, 88, 14, 25]

# 5 数据类型

In [18]:
f = np.array([1,2,3,4,5],dtype=np.int16) 
print(f.itemsize) # 1 np.int8(一个字节)
# 获取数据类型
print(f.dtype)

# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)

# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(),2))

arr = np.array([random.random() for i in range(10)],dtype=np.float16)
# 取小数点后两位
print(np.round(arr,2))
print(arr.dtype)

2
int16
int64
0.07
[0.98 0.95 0.41 0.02 0.96 0.34 0.37 0.68 0.64 0.12]
float16


# 6 数组的计算

### 6.1 数组和数

In [20]:
t1 =np.arange(24).reshape((6,4)) 
print(t1+2)
print("-"*20)
print(t1*2) 
print("-"*20)
print(t1/2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [22]:
#数组与数组的计算
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))

print(t1+t2) 
print("-"*20)
print(t1-t2)

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------
[[-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]]


In [23]:
#形状不一样的数组不能进行计算
t1 = np.arange(24).reshape((4,6)) 
t2 = np.arange(18).reshape((3,6)) 
print(t1)
print(t2) 
print("-"*50)
print(t1-t2) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
--------------------------------------------------


ValueError: operands could not be broadcast together with shapes (4,6) (3,6) 

In [28]:
#数组尺寸不一样，其中一个数组的某一个维度的长度为1，可以进行计算
t1 = np.arange(24).reshape((4,6)) 
t2 = np.arange(0,6).reshape((1,6)) 
print(t1)
print(t2) 
print("-"*50)
print(t1-t2) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]
--------------------------------------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [30]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1)
print(t2) 
print("-"*50)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0]
 [1]
 [2]
 [3]]
--------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [2]:
import numpy as np
t1=np.arange(24).reshape((2,3,4))
t2=np.arange(2).reshape((2,1,1))
print(t1)
print(t2)
print("-"*50)
print(t1-t2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[0]]

 [[1]]]
--------------------------------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [32]:
#6.3 练习轴
a = np.array([[1,2,3],[4,5,6]])
#按那个轴运算，哪个轴就会消失
print(np.sum(a,axis=0)) 

print(np.sum(a,axis=1)) 

print(np.sum(a))

[5 7 9]
[ 6 15]
21


In [35]:
t = np.arange(24) 
print(t.shape)
# 转换成二维
a = t.reshape((2,3,4)) 
a #最外面的方括号是0轴，最内层的方括号是最大轴

(24,)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
b=np.sum(a, axis=0)
print("-"*20)
print(f'b{b.shape}')
c=np.sum(a, axis=1)
print("-"*20)
print(f'c{c.shape}')
d=np.sum(a, axis=2)
print("-"*20)
print(f'd{d.shape}')

--------------------
b(3, 4)
--------------------
c(2, 4)
--------------------
d(2, 3)


# 7 索引和切片

In [41]:
a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2:4])

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2::2])

[2 3]
[2 4 6 8]


In [42]:
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************


In [51]:
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列
print('*'*20)
print(t1[2:4,3:5])# 取某一块区域
print('*'*20)
print(t1[[1,2],[0,2]])

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[[15 16]
 [21 22]]
********************
[ 6 14]


# 8 数组的修改

In [67]:
t = np.arange( 24 ).reshape( 4, 6 )

# # 修改某一行的值
# t[1, :] = 0
#
# # 修改某一列的值
# t[:, 1] = 0
#
# # 修改连续多行
# t[1:3, :] = 0
#
# # 修改连续多列
# t[:, 1:4] = 0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[2,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于10的值改掉
# t[t < 10] = 0
# print(t)
# 使用逻辑判断
# np.logical_and   & # np.logical_or  |
# np.logical_not      ~
# t[(t > 2) & (t < 6)] = 0  # 与
# t[(t < 2) | (t > 6)] = 0  # 或
t[~(t > 6)] = 0  # 非
print(t)


[[ 0  0  0  0  0  0]
 [ 0  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [62]:
t<10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [63]:
t[t < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
t = np.arange( 24 ).reshape( 4, 6 )
t=t.clip(10,18)
print(t)


[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]


In [69]:
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where( score > 80, True, False )
print( result )

[[False  True]
 [ True  True]
 [False  True]]


# 9 数组的添加，删除，去重

In [73]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')

print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0)) #轴是谁，谁就变
print('\n')

print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))


第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [75]:
# 2. numpy.insert
# 函数在给定索引之前，沿给定轴在输入数组中插入值。# 如果值的类型转换为要插入，则它与输入数组不同。
# 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。

a = np.array([[1, 2], [3, 4], [5, 6]])

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 3, [11, 12]))
print('\n')
print('传递了 Axis 参数。 会广播值数组来配输入数组。')

print('沿轴  0 广播：')
print(np.insert(a, 1, [11,12], axis=0))
print('\n')

print('沿轴  1 广播：')
print(np.insert(a, 1, 11, axis=1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴  0 广播：
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]


沿轴  1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [76]:
a = np.arange(12).reshape(3,4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a,5))
print('\n')

print('删除每一行中的第二列：')
print(np.delete(a,1,axis = 1))
print('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




In [78]:
a = np.array([5,2,6,2,7,5,6,8,2,9])

print ('第一个数组：')
print (a)
print ('\n')

print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')



第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]




In [79]:
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')

print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')

print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]
去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


# 10 数组的计算

In [81]:
score = np.array([[80,88],[82,81],[75,81]])
# 1. 获取所有数据最大值
result = np.max(score)
print(result)
# 2. 获取某一个轴上的数据最大值
result = np.max(score,axis=0)
print(result)
# 3. 获取最小值
result = np.min(score,axis=1)
print(result)
# 4. 获取某一个轴上的数据最小值
result = np.min(score,axis=0)
print(result)


88
[82 88]
[80 81 75]
[75 81]


In [85]:
# 5. 数据的比较
result = np.maximum( [-2, -1, 0, 1, 2], 0 )  # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum( [-2, -1, 0, 1, 2], 0 )  # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum( [5, -1, 0, 1, 2], [1, 2, 3, 4, 5] )
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；

# 6. 求平均值
result = np.mean(score) # 获取所有数据的平均值
print(result)
result = np.mean(score,axis=0) # 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr    = np.array([[1,2,3], [4,5,6]])
print(arr)

'''
[1, 2, 3]------>   |1 |2 |3 |
[4, 5, 6]------>   |5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(0))

'''
[1, 2, 3]------>   |1 |2+1   |3+2+1 |
[4, 5, 6]------>   |4 |4+5   |4+5+6 |
'''
print(arr.cumsum(1))


[0 0 0 1 2]
[-2 -1  0  0  0]
[5 2 3 4 5]
81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


In [87]:
# 8. argmin求最小值索引
print(score)
result = np.argmin(score,axis=0)
res=np.min(score,axis=0) #这样我们就可以知道最小的81是第二排的，是从前往后遍历的
print(result,res)

# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score,axis=0)
print(result)

# 10. 极 值
result = np.ptp(score,axis=None)#就是最大值和最小值的差
print(result)

[[80 88]
 [82 81]
 [75 81]]
[2 1] [75 81]
[2.94392029 3.29983165]
13


In [2]:
print(np.log(10)) # 自然对数 e
print(np.log2(10))
print(np.log10(10))

2.302585092994046
3.321928094887362
1.0


# 11 拼接与分割

In [4]:
# 1. 根据轴连接的数组序列
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# 要求a,b两个数组的维度相同
# print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b),axis= 0).shape)
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1).shape)

(4, 2)


沿轴 1 连接两个数组：
(2, 4)


In [7]:
# 2. 根据轴进行堆叠,会增加维度
a =np.arange(12).reshape(3,4)
b =np.arange(12).reshape(3,4)
print ('沿轴 0 连接两个数组：')
print (np.stack((a,b),axis= 0).shape)
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.stack((a,b),axis = 1).shape)

沿轴 0 连接两个数组：
(2, 3, 4)


沿轴 1 连接两个数组：
(3, 2, 4)


In [8]:
# 3. 矩阵垂直拼接，不重要
v1 = [[0,1,2,3,4,5],
   [6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
   [18,19,20,21,22,23]]
result = np.vstack((v1,v2))
print(result)

# 4. 矩阵水平拼接
v1 = [[0,1,2,3,4,5],
   [6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
   [18,19,20,21,22,23]]
result = np.hstack((v1,v2))
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [12]:
#数组的分割
arr = np.arange(9).reshape(3,3)
print(arr)
print ('将数组分为三个大小相等的子数组：')
b = np.split(arr,3,axis=0)
print (b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
将数组分为三个大小相等的子数组：
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [13]:
#不重要
harr = np.floor(10*np.random.random((2, 6))) #floor函数取整,ceil取上整,round四舍五入
print ('原array：')
print(harr)

print ('拆分后：')
print(np.hsplit(harr, 3))

# 3.numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4,4)

print ('第一个数组：')
print (a)
print ('\n')

print ('竖直分割：')
b = np.vsplit(a,2)
print (b)


原array：
[[9. 6. 8. 0. 4. 6.]
 [8. 9. 4. 1. 9. 4.]]
拆分后：
[array([[9., 6.],
       [8., 9.]]), array([[8., 0.],
       [4., 1.]]), array([[4., 6.],
       [9., 4.]])]
第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# 12 nan和inf

In [14]:
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))

nan <class 'float'>
inf <class 'float'>


In [15]:
np.nan == np.nan # nan不等于nan

False

In [18]:
np.inf > -np.inf

True

In [24]:
 # --判断数组中为nan的个数
t = np.arange(24,dtype=float).reshape(4,6)

# 将三行四列的数改成nan
t[3,4] = np.nan
print(t)
t!=t

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]


array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [25]:
np.isnan(t) # 判断是否为nan

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [22]:
# 可以使用np.count_nonzero() 来判断非零的个数
# print(np.count_nonzero(t))
# 并 且  np.nan != np.nan    结果 是TRUE
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.count_nonzero(t != t))

# 将nan替换为0
t[np.isnan(t)] = 0
print(t)

1
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [27]:
np.nan+100

nan

In [28]:
t = np.arange(24).reshape(4,6).astype('float')
#
# 将数组中的一部分替换nan
t[1,3:] = np.nan
print(t)
print('-------------------')
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
   #获取当前列数据
   temp_col = t[:,i]

   # 判断当前列的数据中是否含有nan
   nan_num = np.count_nonzero(temp_col != temp_col)
   # 条件成立说明含有nan
   if nan_num != 0:
      # 将这一列不为nan的数据拿出来
      temp_col_not_nan = temp_col[temp_col == temp_col]
      
      # 将nan替换成这一列的平均值
      temp_col[np.isnan( temp_col )] = np.mean( temp_col_not_nan )
      
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


# 13 转置与轴滚动

In [29]:
a = np.arange(12).reshape(3,4)
print ('原数组：')
print (a )
print ('\n')

print ('对换数组：')
print (np.transpose(a))

# 与transpose一致
a = np.arange(12).reshape(3,4)

print ('原数组：')
print (a)
print ('\n')

print ('转置数组：')
print (a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [30]:
t1 = np.arange(24).reshape(4,6)
re = t1.swapaxes(1,0)
print (' 原 数 组 ：')
print (t1)
print ('\n')

print ('调用 swapaxes 函数后的数组：')
print (re)

 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [32]:
t=np.ones((3,4,5,6))

t1=np.rollaxis(t,2,0)
print(t1.shape)

(5, 3, 4, 6)
